### ISSUE TITLE
pattern description

### ISSUE THREAD

**Issue by JABEZRAJA** [fssa-batch3/meena.subramanian__web_project#3]
### Description of issue
The pattern description is not there in the sign up form

```
Path:      /pages/register%20page/rigister%20page.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kaithari.netlify.app%2Fpages%2Fregister%2520page%2Frigister%2520page.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kaithari.netlify.app/pages/register%20page/rigister%20page.html)

**Comment by vasumeenu004** [comment]
The pattern description is added in the sign up form

**Comment by JABEZRAJA** [comment]
Issue cleared.
