### ISSUE TITLE
Create product

### ISSUE THREAD

**Issue by JABEZRAJA** [fssa-batch3/meena.subramanian__web_project#4]
### Description of issue
The product is not creating.

```
Path:      /pages/seller%20products/seller%20create%20product.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kaithari.netlify.app%2Fpages%2Fseller%2520products%2Fseller%2520create%2520product.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kaithari.netlify.app/pages/seller%20products/seller%20create%20product.html)

**Comment by vasumeenu004** [comment]
The product is creating in the seller product creating page.

**Comment by JABEZRAJA** [comment]
Issue cleared.
