### ISSUE TITLE
PRODUCT IS NOT REMOVED

### ISSUE THREAD

**Issue by JABEZRAJA** [fssa-batch3/meena.subramanian__web_project#5]
### Description of issue
PRODUCT IS NOT REMOVED IN THE ADD AND REMOVE THE PRODUCT LIST FEATURE.

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--kaithari.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--kaithari.netlify.app/)

**Comment by vasumeenu004** [comment]
The product will remove in the add and remove the product feature.

**Comment by JABEZRAJA** [comment]
issue cleared
